$file = 'C:\Users\inbou\victor-ia-tracker\index.html'
$lines = [System.IO.File]::ReadAllLines($file, [System.Text.Encoding]::UTF8)

# ── STEP 1: New head block (replaces original lines 1-7 = indices 0-6)
# Also replaces the old <style> tag at index 7
# New block ends with <style> so CSS goes right after
$newHead = @(
'<!doctype html>',
'<html lang="es-MX">',
'<head>',
'<meta charset="utf-8">',
'<meta name="viewport" content="width=device-width, initial-scale=1">',
'<title>VICTOR IA · Tracker — Panel de Control</title>',
'<meta name="description" content="Panel de control interno de VICTOR IA. Seguimiento de proyectos, finanzas, actividades y performance en tiempo real.">',
'<meta name="robots" content="noindex">',
'<meta name="theme-color" content="#08090D">',
'<meta property="og:title" content="VICTOR IA · Tracker">',
'<meta property="og:description" content="Panel de control interno — proyectos, finanzas y performance en tiempo real.">',
'<meta property="og:image" content="https://victor-ia-tracker.vercel.app/og-tracker.jpg">',
'<meta property="og:type" content="website">',
'<link rel="icon" href="/favicon.ico" type="image/x-icon">',
'<link rel="icon" href="/favicon-32x32.png" sizes="32x32" type="image/png">',
'<link rel="apple-touch-icon" href="/apple-touch-icon.png">',
'<link rel="preconnect" href="https://fonts.googleapis.com">',
'<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>',
'<link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;500;600&family=Fraunces:ital,opsz,wght@0,9..144,300..700;1,9..144,300..700&display=swap" rel="stylesheet">',
'<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>',
'<style>'
)

# ── STEP 2: New CSS block (replaces original CSS content indices 8-788)
$newCSS = @(
'*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }',
':root {',
'  --bg:      #08090D;',
'  --surface: #0F1014;',
'  --surface2: #131418;',
'  --warm:    #F8F7F5;',
'  --bone:    rgba(248,247,245,0.92);',
'  --bone2:   rgba(248,247,245,0.50);',
'  --bone3:   rgba(248,247,245,0.07);',
'  --amber:   #CC8800;',
'  --amber2:  rgba(204,136,0,0.14);',
'  --amber3:  rgba(204,136,0,0.07);',
'  --green:   #4ade80;',
'  --red:     #f87171;',
'  --blue:    #60a5fa;',
'  --purple:  #c084fc;',
'  --border:  rgba(248,247,245,0.09);',
'  --radius:  2px;',
'  --ink:     #F8F7F5;',
'}',
'',
'html { scroll-behavior: smooth; }',
'body {',
"  font-family: 'Space Grotesk', sans-serif;",
'  background: var(--bg);',
'  color: var(--bone);',
'  min-height: 100vh;',
'  font-size: 14px;',
'  -webkit-font-smoothing: antialiased;',
'}',
'a { color: inherit; text-decoration: none; }',
'button { cursor: pointer; border: none; outline: none; font-family: inherit; }',
'input, select, textarea { font-family: inherit; font-size: 14px; outline: none; }',
'',
'/* ── Marble texture overlay (subtle) ── */',
'body::before {',
"  content: '';",
'  position: fixed; inset: 0; z-index: 0; pointer-events: none;',
"  background: url('https://victor-ia-website.vercel.app/assets/bg-light.jpg') center/cover;",
'  opacity: 0.022;',
'}',
'',
'/* ── TOPBAR ── */',
'#topbar {',
'  display: flex; align-items: center; gap: 16px;',
'  padding: 0 clamp(1.2rem,3vw,2.5rem);',
'  height: 58px;',
'  background: var(--surface);',
'  border-bottom: 1px solid var(--border);',
'  position: sticky; top: 0; z-index: 100;',
'  flex-wrap: wrap;',
'  position: relative; z-index: 100;',
'}',
'.via-logo-wrap { display: flex; align-items: center; flex-shrink: 0; }',
'#topbar .badge {',
'  background: var(--amber2);',
'  border: 1px solid rgba(204,136,0,0.4);',
'  color: var(--amber);',
'  font-size: 9px; padding: 2px 7px;',
'  letter-spacing: 0.18em; text-transform: uppercase; font-weight: 600;',
'}',
'#topbar .spacer { flex: 1; }',
'#topbar .topbar-btns { display: flex; gap: 6px; flex-wrap: wrap; }',
'#topbar .topbar-btns button {',
'  background: transparent;',
'  border: 1px solid var(--border);',
'  color: var(--bone2);',
'  padding: 6px 14px;',
'  font-size: 11px; letter-spacing: 0.14em; text-transform: uppercase;',
'  transition: all 0.22s;',
'}',
'#topbar .topbar-btns button:hover {',
'  border-color: rgba(204,136,0,0.5);',
'  color: var(--amber);',
'}',
'',
'/* ── PERIOD BAR ── */',
'#period-bar {',
'  display: flex; align-items: center; gap: 6px;',
'  padding: 8px clamp(1.2rem,3vw,2.5rem);',
'  background: var(--surface);',
'  border-bottom: 1px solid var(--border);',
'  position: sticky; top: 58px; z-index: 99; flex-wrap: wrap;',
'}',
'#period-bar .period-label {',
'  font-size: 10px; color: var(--bone2); font-weight: 500;',
'  text-transform: uppercase; letter-spacing: 0.25em; margin-right: 4px;',
'}',
'.period-btn {',
'  padding: 4px 12px;',
'  font-size: 10px; font-weight: 500; letter-spacing: 0.12em; text-transform: uppercase;',
'  background: transparent;',
'  border: 1px solid var(--border);',
'  color: var(--bone2);',
'  transition: all 0.2s;',
'}',
'.period-btn:hover { border-color: rgba(204,136,0,0.4); color: var(--amber); }',
'.period-btn.active {',
'  background: var(--amber2);',
'  border-color: rgba(204,136,0,0.5);',
'  color: var(--amber);',
'}',
'#period-custom { display: none; gap: 8px; align-items: center; }',
'#period-custom.show { display: flex; }',
'#period-custom input {',
'  background: var(--surface2); border: 1px solid var(--border);',
'  color: var(--bone); padding: 4px 8px; font-size: 11px;',
'}',
'#period-custom button {',
'  background: var(--amber); color: #000;',
'  padding: 4px 12px; font-size: 10px; font-weight: 700; letter-spacing: 0.12em;',
'}',
'#period-summary { font-size: 10px; color: var(--bone2); margin-left: auto; letter-spacing: 0.1em; }',
'',
'/* ── PROJECT BAR ── */',
'#project-bar {',
'  display: flex; align-items: center; gap: 8px;',
'  padding: 6px clamp(1.2rem,3vw,2.5rem);',
'  background: var(--bg);',
'  border-bottom: 1px solid var(--border);',
'  position: sticky; top: 108px; z-index: 97;',
'  flex-wrap: wrap; transition: background 0.3s;',
'}',
'#project-bar.proj-active { background: rgba(204,136,0,0.05); border-bottom-color: rgba(204,136,0,0.2); }',
'.proj-label {',
'  font-size: 10px; color: var(--bone2); font-weight: 500;',
'  text-transform: uppercase; letter-spacing: 0.22em; white-space: nowrap;',
'}',
'.proj-btn {',
'  padding: 3px 11px;',
'  font-size: 10px; font-weight: 500; letter-spacing: 0.12em; text-transform: uppercase;',
'  background: transparent; border: 1px solid var(--border); color: var(--bone2);',
'  transition: all 0.2s; cursor: pointer; white-space: nowrap;',
'  max-width: 200px; overflow: hidden; text-overflow: ellipsis;',
'}',
'.proj-btn:hover { border-color: rgba(204,136,0,0.4); color: var(--amber); }',
'.proj-btn.active { background: var(--amber2); border-color: rgba(204,136,0,0.4); color: var(--amber); }',
'#proj-summary { font-size: 10px; color: var(--amber); margin-left: auto; font-weight: 500; letter-spacing: 0.1em; display: none; }',
'#project-bar.proj-active #proj-summary { display: block; }',
'',
'/* ── TABS ── */',
'#tabs {',
'  display: flex; gap: 0;',
'  padding: 0 clamp(1.2rem,3vw,2.5rem);',
'  background: var(--surface);',
'  border-bottom: 1px solid var(--border);',
'  position: sticky; top: 148px; z-index: 98;',
'  overflow-x: auto;',
'}',
'.tab-btn {',
'  padding: 12px 18px;',
'  font-size: 11px; font-weight: 500; letter-spacing: 0.15em; text-transform: uppercase;',
'  color: var(--bone2);',
'  background: transparent;',
'  border-bottom: 1px solid transparent;',
'  transition: all 0.22s; white-space: nowrap;',
'}',
'.tab-btn:hover { color: var(--bone); }',
'.tab-btn.active { color: var(--amber); border-bottom-color: var(--amber); }',
'',
'/* ── LAYOUT ── */',
'#main { display: flex; min-height: calc(100vh - 198px); position: relative; z-index: 1; }',
'#sidebar {',
'  width: 268px; min-width: 268px;',
'  background: var(--surface);',
'  border-right: 1px solid var(--border);',
'  padding: 20px;',
'  overflow-y: auto; max-height: calc(100vh - 198px);',
'  position: sticky; top: 198px;',
'}',
'#sidebar.hidden { display: none; }',
'#content { flex: 1; padding: 20px clamp(1.2rem,3vw,2.5rem); overflow-y: auto; max-height: calc(100vh - 198px); }',
'',
'/* ── SIDEBAR ── */',
'.sidebar-title {',
'  font-size: 9px; font-weight: 600; letter-spacing: 0.3em;',
'  color: var(--amber); text-transform: uppercase; margin-bottom: 12px;',
'}',
'.filter-group { margin-bottom: 16px; }',
'.filter-group label {',
'  display: block; font-size: 10px; color: var(--bone2);',
'  margin-bottom: 5px; font-weight: 500; letter-spacing: 0.12em; text-transform: uppercase;',
'}',
'.filter-group input, .filter-group select {',
'  width: 100%; background: var(--surface2);',
'  border: 1px solid var(--border); color: var(--bone);',
'  padding: 7px 10px; font-size: 12px;',
'}',
'.filter-group input:focus, .filter-group select:focus { border-color: rgba(204,136,0,0.5); }',
'.filter-group input[type=range] { padding: 0; height: 24px; }',
".range-val { font-size: 11px; color: var(--amber); text-align: center; margin-top: 2px; font-family: 'Fraunces', serif; }",
'.filter-actions { display: flex; gap: 6px; margin-top: 4px; }',
'.filter-actions button { flex: 1; padding: 7px; font-size: 10px; font-weight: 600; letter-spacing: 0.12em; text-transform: uppercase; }',
'.btn-apply { background: var(--amber); color: #08090D; }',
'.btn-clear { background: var(--surface2); border: 1px solid var(--border); color: var(--bone2); }',
'',
'/* ── KPI CARDS ── */',
'.kpi-grid { display: grid; grid-template-columns: repeat(auto-fill,minmax(160px,1fr)); gap: 1px; margin-bottom: 20px; background: var(--border); }',
'.kpi-card {',
'  background: var(--surface); border: none;',
'  padding: 18px 16px; position: relative; overflow: hidden;',
'}',
'.kpi-card.hero::before {',
"  content: ''; position: absolute; top: 0; left: 0; right: 0;",
'  height: 1px; background: var(--amber);',
'}',
'.kpi-label {',
'  font-size: 9px; color: var(--bone2); font-weight: 500;',
'  letter-spacing: 0.28em; text-transform: uppercase; margin-bottom: 8px;',
'}',
'.kpi-val {',
"  font-family: 'Fraunces', serif;",
'  font-size: 2.4rem; font-weight: 400; font-style: italic;',
'  color: var(--amber); line-height: 1; letter-spacing: -0.02em;',
'}',
'.kpi-sub { font-size: 10px; color: var(--bone2); margin-top: 5px; letter-spacing: 0.08em; }',
'.kpi-trend { position: absolute; top: 16px; right: 16px; font-size: 16px; }',
'',
'/* ── SECTION HEADERS ── */',
'.section-title {',
'  font-size: 9px; font-weight: 500; letter-spacing: 0.3em;',
'  color: var(--amber); text-transform: uppercase; margin-bottom: 14px;',
'  display: flex; align-items: center; gap: 10px;',
'}',
".section-title::after { content: ''; flex: 1; height: 1px; background: var(--border); }",
'',
'/* ── CHARTS ── */',
'.chart-grid { display: grid; grid-template-columns: repeat(auto-fill,minmax(320px,1fr)); gap: 1px; margin-bottom: 20px; background: var(--border); }',
'.chart-card { background: var(--surface); padding: 20px; }',
'.chart-card h3 {',
'  font-size: 9px; color: var(--bone2); font-weight: 500;',
'  margin-bottom: 14px; text-transform: uppercase; letter-spacing: 0.25em;',
'}',
'.chart-wrap { position: relative; height: 200px; }',
'.chart-wrap canvas { max-height: 200px; }',
'',
'/* ── BARS ── */',
'.bar-list { display: flex; flex-direction: column; gap: 10px; }',
'.bar-item { display: flex; align-items: center; gap: 10px; }',
'.bar-label { min-width: 110px; font-size: 11px; color: var(--bone2); white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }',
'.bar-track { flex: 1; height: 2px; background: var(--bone3); overflow: hidden; }',
'.bar-fill { height: 100%; background: var(--amber); transition: width 0.5s cubic-bezier(0.16,1,0.3,1); }',
".bar-val { min-width: 50px; text-align: right; font-size: 11px; color: var(--bone); font-weight: 500; font-family: 'Fraunces', serif; }",
'',
'/* ── TABLE ── */',
'.table-wrap { overflow-x: auto; margin-bottom: 20px; }',
'table { width: 100%; border-collapse: collapse; }',
'th {',
'  padding: 10px 12px; text-align: left;',
'  font-size: 9px; font-weight: 500; letter-spacing: 0.25em; color: var(--bone2);',
'  text-transform: uppercase; border-bottom: 1px solid var(--border); cursor: pointer; white-space: nowrap;',
'}',
'th:hover { color: var(--amber); }',
'td { padding: 10px 12px; border-bottom: 1px solid var(--border); font-size: 12px; vertical-align: middle; }',
'tr:hover td { background: var(--amber3); }',
'.tag { display: inline-block; padding: 2px 7px; font-size: 9px; font-weight: 600; letter-spacing: 0.1em; margin: 1px; text-transform: uppercase; }',
'.tag-dev { background: rgba(59,130,246,.15); color: #93c5fd; }',
'.tag-mkt { background: rgba(168,85,247,.15); color: #d8b4fe; }',
'.tag-des { background: rgba(34,197,94,.15); color: #86efac; }',
'.tag-ai { background: var(--amber2); color: var(--amber); }',
'.tag-ops { background: rgba(239,68,68,.15); color: #fca5a5; }',
'.tag-vid { background: rgba(20,184,166,.15); color: #5eead4; }',
'.badge-status { display: inline-block; padding: 2px 8px; font-size: 9px; font-weight: 600; letter-spacing: 0.1em; text-transform: uppercase; }',
'.s-done { background: rgba(34,197,94,.12); color: var(--green); }',
'.s-prog { background: rgba(59,130,246,.12); color: var(--blue); }',
'.s-rev { background: rgba(239,68,68,.12); color: var(--red); }',
'.pagination { display: flex; align-items: center; gap: 6px; justify-content: flex-end; padding: 10px 0; flex-wrap: wrap; }',
'.pagination button { background: var(--surface2); border: 1px solid var(--border); color: var(--bone2); padding: 5px 10px; font-size: 10px; letter-spacing: 0.12em; }',
'.pagination button:hover:not(:disabled) { border-color: rgba(204,136,0,0.4); color: var(--amber); }',
'.pagination button:disabled { opacity: 0.3; }',
'.pagination span { font-size: 11px; color: var(--bone2); }',
'.sort-icon { font-size: 9px; margin-left: 3px; }',
'',
'/* ── HEATMAP ── */',
'.heatmap-grid { display: grid; grid-template-columns: repeat(7,1fr); gap: 3px; margin-bottom: 8px; }',
'.hm-cell { height: 26px; display: flex; align-items: center; justify-content: center; font-size: 9px; color: var(--bone2); }',
'.hm-0 { background: var(--bone3); }',
'.hm-1 { background: rgba(204,136,0,0.22); }',
'.hm-2 { background: rgba(204,136,0,0.42); }',
'.hm-3 { background: rgba(204,136,0,0.65); }',
'.hm-4 { background: rgba(204,136,0,0.88); }',
'.hm-days { display: grid; grid-template-columns: repeat(7,1fr); gap: 3px; margin-bottom: 4px; }',
'.hm-day { text-align: center; font-size: 9px; color: var(--bone2); letter-spacing: 0.1em; }',
'',
'/* ── SOFTWARE TABLE ── */',
'.sw-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }',
'.sw-table th { padding: 9px 12px; text-align: left; font-size: 9px; font-weight: 500; letter-spacing: 0.25em; color: var(--amber); text-transform: uppercase; border-bottom: 1px solid var(--border); }',
'.sw-table td { padding: 11px 12px; border-bottom: 1px solid var(--border); font-size: 12px; }',
'.sw-table tr:hover td { background: var(--amber3); }',
'.sw-type { display: inline-block; padding: 2px 7px; font-size: 9px; font-weight: 600; letter-spacing: 0.1em; text-transform: uppercase; }',
'.type-api { background: rgba(59,130,246,.15); color: #93c5fd; }',
'.type-saas { background: rgba(34,197,94,.15); color: #86efac; }',
'.type-free { background: rgba(248,247,245,.08); color: var(--bone2); }',
'.cost-bar-mini { height: 2px; background: var(--bone3); margin-top: 4px; overflow: hidden; }',
'.cost-bar-fill { height: 100%; background: var(--amber); }',
'',
'/* ── DASHBOARD STRIPS ── */',
'.today-bar {',
'  background: var(--surface);',
'  border: none; border-left: 1px solid var(--amber);',
'  padding: 14px 18px; margin-bottom: 18px;',
'  display: flex; align-items: center; gap: 18px; flex-wrap: wrap;',
'}',
'.today-bar .tstat { display: flex; flex-direction: column; min-width: 80px; }',
'.today-bar .tstat .tv {',
"  font-family: 'Fraunces', serif;",
'  font-size: 1.8rem; font-weight: 400; font-style: italic;',
'  color: var(--amber); line-height: 1;',
'}',
'.today-bar .tstat .tl { font-size: 9px; color: var(--bone2); font-weight: 500; text-transform: uppercase; letter-spacing: 0.22em; margin-top: 3px; }',
'.today-divider { width: 1px; height: 36px; background: var(--border); }',
'',
'/* ── GROWTH HACKING STRIP ── */',
'.gh-strip {',
'  display: flex; align-items: stretch; gap: 0;',
'  background: var(--border); margin-bottom: 16px;',
'  overflow: hidden; flex-wrap: wrap;',
'}',
'.gh-item {',
'  display: flex; align-items: center; gap: 10px;',
'  padding: 12px 16px; flex: 1; min-width: 130px;',
'  background: var(--surface);',
'  border-right: 1px solid var(--border);',
'  position: relative; overflow: hidden;',
'}',
'.gh-icon { font-size: 18px; flex-shrink: 0; }',
".gh-val { font-family: 'Fraunces', serif; font-size: 1.4rem; font-weight: 400; font-style: italic; color: var(--amber); line-height: 1; }",
'.gh-unit { font-size: 10px; font-weight: 500; color: var(--bone2); margin-left: 2px; }',
'.gh-label { font-size: 9px; color: var(--bone2); font-weight: 500; text-transform: uppercase; letter-spacing: 0.22em; margin-top: 2px; }',
'.gh-trend-up { color: var(--green); font-size: 11px; font-weight: 600; }',
'.gh-trend-dn { color: var(--red); font-size: 11px; font-weight: 600; }',
'.gh-trend-eq { color: var(--bone2); font-size: 11px; }',
'.gh-insight { flex: 2; min-width: 180px; padding: 12px 16px; display: flex; align-items: center; gap: 8px; font-size: 12px; color: var(--bone); border-right: none; background: var(--surface); }',
'.gh-insight-icon { font-size: 16px; flex-shrink: 0; }',
'.gh-insight-text { line-height: 1.45; flex: 1; }',
'.gh-insight-text strong { color: var(--amber); }',
'',
'/* ── FEED ── */',
'.feed-list { display: flex; flex-direction: column; gap: 0; }',
'.feed-item { display: flex; gap: 12px; padding: 12px 0; border-bottom: 1px solid var(--border); }',
'.feed-dot { width: 6px; height: 6px; border-radius: 50%; background: var(--amber); margin-top: 5px; flex-shrink: 0; }',
'.feed-dot.rework { background: var(--red); }',
'.feed-time { font-size: 10px; color: var(--bone2); white-space: nowrap; min-width: 40px; font-variant-numeric: tabular-nums; }',
'.feed-body { flex: 1; }',
'.feed-desc { font-size: 13px; color: var(--bone); margin-bottom: 2px; }',
'.feed-obs { font-size: 11px; color: var(--amber); font-style: italic; margin-top: 2px; }',
'.feed-meta { font-size: 10px; color: var(--bone2); margin-top: 2px; letter-spacing: 0.06em; }',
".feed-cost { font-size: 11px; color: var(--green); font-weight: 600; margin-top: 2px; font-family: 'Fraunces', serif; }",
'.feed-pricing-row { display: flex; align-items: center; gap: 6px; margin-top: 4px; flex-wrap: wrap; }',
'.feed-price-tag { font-size: 9px; font-weight: 600; padding: 2px 7px; white-space: nowrap; letter-spacing: 0.1em; text-transform: uppercase; }',
'.feed-price-tag.cost { color: #f97316; background: rgba(249,115,22,.1); }',
'.feed-price-tag.price { color: var(--green); background: rgba(74,222,128,.1); }',
'.feed-price-tag.margin { color: var(--amber); background: var(--amber2); }',
'.feed-price-tag em { font-style: normal; opacity: 0.7; }',
'.feed-price-sep { color: var(--border); font-size: 12px; }',
'body.client-mode .internal-only { display: none !important; }',
'body.client-mode #client-mode-btn { background: var(--amber); color: #08090D; font-weight: 700; }',
'.client-mode-banner { display: none; background: var(--amber2); border-bottom: 1px solid rgba(204,136,0,0.3); color: var(--amber); font-size: 10px; font-weight: 500; text-align: center; padding: 6px; letter-spacing: 0.25em; text-transform: uppercase; }',
'body.client-mode .client-mode-banner { display: block; }',
'.feed-sw { display: flex; gap: 4px; flex-wrap: wrap; margin-top: 4px; }',
'.feed-sw-tag { background: var(--amber3); border: 1px solid rgba(204,136,0,.2); color: var(--amber); font-size: 9px; padding: 1px 6px; letter-spacing: 0.1em; text-transform: uppercase; }',
'',
'/* ── PROMPT ENGINEERING ── */',
'.prompt-badge { display: inline-flex; align-items: center; gap: 3px; padding: 1px 7px; font-size: 9px; font-weight: 600; margin-top: 3px; letter-spacing: 0.1em; text-transform: uppercase; }',
'.prompt-1 { background: rgba(34,197,94,.12); color: var(--green); border: 1px solid rgba(34,197,94,.25); }',
'.prompt-2 { background: rgba(59,130,246,.12); color: var(--blue); border: 1px solid rgba(59,130,246,.25); }',
'.prompt-3 { background: var(--amber2); color: var(--amber); border: 1px solid rgba(204,136,0,.3); }',
'.prompt-high { background: rgba(239,68,68,.12); color: var(--red); border: 1px solid rgba(239,68,68,.25); }',
'.prompt-winner { font-size: 10px; color: var(--blue); font-style: italic; margin-top: 3px; padding: 4px 8px; background: rgba(59,130,246,.06); border-left: 2px solid var(--blue); }',
'.prompt-section { margin-top: 16px; padding: 14px; background: var(--surface2); border: 1px solid var(--border); border-left: 2px solid var(--blue); }',
'.prompt-section h4 { font-size: 9px; font-weight: 600; color: var(--blue); text-transform: uppercase; letter-spacing: 0.28em; margin-bottom: 10px; }',
'.peff-grid { display: grid; grid-template-columns: repeat(auto-fill,minmax(130px,1fr)); gap: 1px; margin-bottom: 14px; background: var(--border); }',
'.peff-card { background: var(--surface); padding: 12px; text-align: center; }',
".peff-val { font-family: 'Fraunces', serif; font-size: 1.6rem; font-weight: 400; font-style: italic; line-height: 1; margin-bottom: 3px; }",
'.peff-label { font-size: 9px; color: var(--bone2); font-weight: 500; text-transform: uppercase; letter-spacing: 0.22em; }',
'',
'/* ── FLOWCHART ── */',
'.fl-outer { background: var(--surface2); padding: 20px; }',
'.fl-heading { font-size: 10px; font-weight: 600; letter-spacing: 0.25em; color: var(--bone); text-transform: uppercase; margin-bottom: 16px; }',
'.fl-section-title { font-size: 9px; color: var(--bone2); letter-spacing: 0.22em; text-transform: uppercase; font-weight: 500; margin-bottom: 8px; padding-left: 2px; }',
'.fl-pipe-row { display: flex; align-items: center; gap: 8px; flex-wrap: wrap; }',
'.fl-card { background: color-mix(in srgb,var(--fc,#CC8800) 10%,transparent); border: 1px solid var(--fc,#CC8800); padding: 10px 14px; cursor: pointer; text-align: left; min-width: 100px; transition: all 0.22s; color: inherit; font-family: inherit; flex-shrink: 0; }',
'.fl-card:hover { background: color-mix(in srgb,var(--fc,#CC8800) 22%,transparent); transform: translateY(-1px); }',
'.fl-card-title { font-size: 11px; font-weight: 600; color: var(--fc,#CC8800); line-height: 1.3; letter-spacing: 0.06em; }',
'.fl-card-sub { font-size: 10px; color: var(--bone2); margin-top: 3px; }',
'.fl-pipe-arrow { color: var(--border); font-size: 18px; flex-shrink: 0; line-height: 1; user-select: none; }',
'.fl-divider { display: flex; gap: 8px; flex-wrap: wrap; padding: 10px 0; border-top: 1px solid var(--border); border-bottom: 1px solid var(--border); margin: 14px 0; }',
'.fl-divider-badge { font-size: 9px; color: var(--bone2); background: var(--bone3); padding: 3px 8px; letter-spacing: 0.12em; text-transform: uppercase; }',
'.fl-feedback-row { display: flex; gap: 20px; flex-wrap: wrap; align-items: flex-start; }',
'.fl-fb-group { flex: 1; min-width: 200px; }',
'.fl-fb-label { font-size: 10px; color: var(--bone2); margin-bottom: 8px; font-weight: 500; letter-spacing: 0.1em; }',
'.fl-fb-sublabel { font-size: 10px; color: rgba(248,247,245,0.3); margin-top: 6px; font-style: italic; }',
'.fl-footer { font-size: 9px; color: rgba(248,247,245,0.25); margin-top: 14px; text-align: center; letter-spacing: 0.2em; text-transform: uppercase; }',
'',
'/* ── REPORTES ── */',
'.rep-dept-grid { display: grid; grid-template-columns: repeat(auto-fill,minmax(260px,1fr)); gap: 1px; margin-bottom: 8px; background: var(--border); }',
'.rep-dept-card { background: var(--surface2); padding: 14px; border-top: 1px solid var(--dc,#CC8800); }',
'.rep-dept-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px; }',
'.rep-dept-name { font-size: 11px; font-weight: 600; letter-spacing: 0.12em; text-transform: uppercase; }',
".rep-dept-pct { font-size: 11px; font-weight: 500; color: var(--bone2); font-family: 'Fraunces', serif; }",
'.rep-dept-bar { height: 1px; background: var(--bone3); margin-bottom: 10px; overflow: hidden; }',
'.rep-dept-bar-fill { height: 100%; transition: width 0.5s cubic-bezier(0.16,1,0.3,1); }',
'.rep-dept-stats { display: flex; gap: 12px; font-size: 10px; color: var(--bone2); margin-bottom: 10px; font-weight: 500; letter-spacing: 0.08em; }',
'.rep-dept-actions { display: flex; flex-direction: column; gap: 4px; }',
'.rep-dept-action { display: grid; grid-template-columns: 72px 1fr auto; gap: 6px; align-items: center; font-size: 10px; padding: 4px 0; border-top: 1px solid var(--border); }',
".rep-da-date { color: rgba(248,247,245,0.35); font-family: 'Space Grotesk', monospace; font-size: 9px; }",
'.rep-da-desc { color: var(--bone2); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }',
".rep-da-dur { color: var(--amber); font-weight: 600; white-space: nowrap; font-family: 'Fraunces', serif; }",
'.rep-dept-more { font-size: 9px; color: rgba(248,247,245,0.25); text-align: center; padding-top: 4px; letter-spacing: 0.15em; text-transform: uppercase; }',
'.rep-daily { display: flex; flex-direction: column; gap: 16px; }',
'.rep-day-card { background: var(--surface2); border-top: 1px solid var(--border); overflow: hidden; }',
'.rep-day-header { display: flex; justify-content: space-between; align-items: center; padding: 12px 16px; background: rgba(248,247,245,.03); flex-wrap: wrap; gap: 8px; }',
'.rep-day-date { display: flex; flex-direction: column; gap: 2px; }',
".rep-day-label { font-family: 'Fraunces', serif; font-size: 1.1rem; font-weight: 400; color: var(--bone); text-transform: capitalize; }",
'.rep-day-key { font-size: 9px; color: var(--bone2); letter-spacing: 0.18em; text-transform: uppercase; }',
'.rep-day-totals { display: flex; gap: 10px; flex-wrap: wrap; }',
".rep-day-stat { font-family: 'Fraunces', serif; font-size: 11px; font-weight: 400; color: var(--amber); background: var(--amber2); padding: 3px 8px; }",
'.rep-day-timeline { padding: 0 16px 12px; }',
'.rep-timeline-row { display: grid; grid-template-columns: 44px 8px 1fr; gap: 8px; align-items: start; padding: 10px 0; border-bottom: 1px solid var(--border); }',
'.rep-timeline-row:last-child { border-bottom: none; }',
'.rep-tl-time { font-size: 10px; color: rgba(248,247,245,0.4); padding-top: 2px; text-align: right; font-variant-numeric: tabular-nums; }',
'.rep-tl-dot { width: 8px; height: 8px; border-radius: 50%; margin-top: 3px; flex-shrink: 0; }',
'.rep-tl-body { flex: 1; min-width: 0; }',
'.rep-tl-desc { font-size: 12px; font-weight: 500; color: var(--bone); line-height: 1.4; margin-bottom: 4px; }',
'.rep-tl-meta { display: flex; gap: 8px; flex-wrap: wrap; align-items: center; }',
'.rep-tl-cat { font-size: 9px; font-weight: 600; letter-spacing: 0.1em; text-transform: uppercase; }',
'.rep-tl-proj { font-size: 10px; color: rgba(248,247,245,0.35); }',
'',
'/* ── MODALS (generic) ── */',
'.fm-overlay { position: fixed; inset: 0; background: rgba(8,9,13,0.85); z-index: 500; display: none; align-items: center; justify-content: center; padding: 20px; backdrop-filter: blur(4px); }',
'.fm-overlay.open { display: flex; }',
'.fm-panel { background: var(--surface); border: 1px solid var(--border); width: 100%; max-height: 90vh; overflow-y: auto; }',
'.fm-header { display: flex; justify-content: space-between; align-items: center; padding: 16px 20px; border-bottom: 1px solid var(--border); }',
'.fm-title { font-size: 11px; font-weight: 600; letter-spacing: 0.2em; text-transform: uppercase; color: var(--bone); }',
'.fm-close, .fm-action { background: transparent; border: 1px solid var(--border); color: var(--bone2); padding: 5px 12px; font-size: 10px; letter-spacing: 0.12em; text-transform: uppercase; cursor: pointer; transition: all 0.2s; }',
'.fm-close:hover { border-color: var(--red); color: var(--red); }',
'.fm-action-btn { display: flex; flex-direction: column; gap: 4px; padding: 16px; background: var(--surface2); border: 1px solid var(--border); cursor: pointer; text-align: left; color: var(--bone); font-family: inherit; transition: all 0.22s; }',
'.fm-action-btn:hover { border-color: rgba(204,136,0,0.4); background: var(--amber3); }',
'.fm-action-icon { font-size: 20px; margin-bottom: 4px; }',
'',
'/* ── CLIENT PANEL ── */',
'.cp-overlay { position: fixed; inset: 0; background: var(--bg); z-index: 600; display: none; flex-direction: column; }',
'.cp-overlay.open { display: flex; }',
'.cp-topbar { display: flex; align-items: center; gap: 12px; padding: 0 clamp(1.2rem,3vw,2.5rem); height: 58px; background: var(--surface); border-bottom: 1px solid var(--border); }',
".cp-logo { font-family: 'Fraunces', serif; font-size: 1.1rem; font-weight: 400; letter-spacing: -0.01em; }",
'.cp-badge { font-size: 9px; font-weight: 500; letter-spacing: 0.22em; text-transform: uppercase; color: var(--amber); background: var(--amber2); padding: 2px 8px; border: 1px solid rgba(204,136,0,0.3); }',
'.cp-close-btn { margin-left: auto; background: transparent; border: 1px solid var(--border); color: var(--bone2); padding: 6px 14px; font-size: 10px; letter-spacing: 0.15em; text-transform: uppercase; cursor: pointer; }',
'.cp-close-btn:hover { border-color: var(--red); color: var(--red); }',
'.cp-body { flex: 1; overflow-y: auto; padding: 20px clamp(1.2rem,3vw,2.5rem); }',
'',
'/* ── MISC ELEMENTS ── */',
'.add-form { background: var(--surface); border-top: 1px solid var(--border); padding: 16px clamp(1.2rem,3vw,2.5rem); display: none; }',
'.add-form.open { display: block; }',
'.add-grid { display: grid; grid-template-columns: repeat(auto-fill,minmax(200px,1fr)); gap: 12px; margin-bottom: 14px; }',
'.add-field { display: flex; flex-direction: column; gap: 5px; }',
'.add-field label { font-size: 9px; color: var(--bone2); font-weight: 500; letter-spacing: 0.22em; text-transform: uppercase; }',
'.add-field input, .add-field select, .add-field textarea { background: var(--surface2); border: 1px solid var(--border); color: var(--bone); padding: 8px 10px; font-size: 12px; width: 100%; }',
'.add-field input:focus, .add-field select:focus, .add-field textarea:focus { border-color: rgba(204,136,0,0.5); }',
'.add-actions { display: flex; gap: 8px; }',
'.btn-save { background: var(--amber); color: #08090D; padding: 9px 22px; font-size: 10px; font-weight: 700; letter-spacing: 0.18em; text-transform: uppercase; cursor: pointer; }',
'.btn-cancel-add { background: transparent; border: 1px solid var(--border); color: var(--bone2); padding: 9px 18px; font-size: 10px; letter-spacing: 0.15em; text-transform: uppercase; cursor: pointer; }',
'',
'/* ── SETTINGS PANEL ── */',
'.settings-panel { position: fixed; inset: 0; background: rgba(8,9,13,0.85); z-index: 500; display: none; align-items: center; justify-content: center; padding: 20px; backdrop-filter: blur(4px); }',
'.settings-panel.open { display: flex; }',
'.settings-box { background: var(--surface); border: 1px solid var(--border); width: 100%; max-width: 600px; max-height: 80vh; overflow-y: auto; }',
'.settings-header { display: flex; justify-content: space-between; align-items: center; padding: 16px 20px; border-bottom: 1px solid var(--border); }',
'.settings-title { font-size: 10px; font-weight: 600; letter-spacing: 0.28em; text-transform: uppercase; color: var(--bone); }',
'.settings-body { padding: 20px; }',
'.settings-group { margin-bottom: 20px; }',
'.settings-group-title { font-size: 9px; font-weight: 500; color: var(--amber); letter-spacing: 0.28em; text-transform: uppercase; margin-bottom: 10px; }',
'.settings-row { display: flex; justify-content: space-between; align-items: center; padding: 8px 0; border-bottom: 1px solid var(--border); font-size: 12px; }',
'.settings-row label { color: var(--bone2); font-size: 11px; }',
'',
'/* ── PLANEACION (PM) ── */',
'.pm-agent-bar { display: none; background: rgba(204,136,0,0.08); border: 1px solid rgba(204,136,0,0.25); padding: 10px 12px; margin-top: 10px; border-radius: 0; display: flex; gap: 10px; align-items: center; }',
'.pm-agent-bar.active { display: flex; }',
'.pm-agent-state { font-size: 10px; font-weight: 600; color: var(--amber); letter-spacing: 0.15em; text-transform: uppercase; }',
'.pm-agent-transcript { font-size: 12px; color: var(--bone2); flex: 1; font-style: italic; }',
'.pm-agent-stop { background: transparent; border: 1px solid var(--border); color: var(--bone2); padding: 4px 10px; font-size: 10px; letter-spacing: 0.12em; cursor: pointer; }',
'',
'/* ── ORGANIGRAMA ── */',
'.org-grid { display: grid; grid-template-columns: repeat(auto-fill,minmax(220px,1fr)); gap: 1px; background: var(--border); margin-bottom: 20px; }',
'.org-card { background: var(--surface); padding: 16px; border-top: 1px solid var(--dc,#CC8800); }',
'.org-role { font-size: 9px; color: var(--bone2); font-weight: 500; letter-spacing: 0.22em; text-transform: uppercase; margin-bottom: 4px; }',
".org-name { font-family: 'Fraunces', serif; font-size: 1.1rem; font-weight: 400; letter-spacing: -0.01em; margin-bottom: 8px; }",
'.org-stats { font-size: 10px; color: var(--bone2); line-height: 1.7; }',
'',
'/* ── SCROLL / MISC ── */',
'::-webkit-scrollbar { width: 4px; height: 4px; }',
'::-webkit-scrollbar-track { background: transparent; }',
'::-webkit-scrollbar-thumb { background: var(--border); }',
'::-webkit-scrollbar-thumb:hover { background: rgba(248,247,245,0.18); }',
'::selection { background: var(--amber); color: #08090D; }',
'.hidden { display: none !important; }',
'.auto-live-indicator { display: none; background: rgba(74,222,128,0.12); border: 1px solid rgba(74,222,128,0.4); color: var(--green); font-size: 9px; padding: 2px 8px; font-weight: 600; letter-spacing: 0.15em; text-transform: uppercase; animation: livePulse 2s ease-in-out infinite; }',
'@keyframes livePulse { 0%,100%{opacity:0.6} 50%{opacity:1} }',
'@keyframes pulse { 0%,100%{opacity:0.5} 50%{opacity:1} }',
'',
'/* ── RESPONSIVE ── */',
'@media (max-width: 960px) {',
'  #sidebar { display: none; }',
'  #sidebar.force-show { display: block; position: fixed; top: 198px; left: 0; z-index: 200; height: calc(100vh - 198px); box-shadow: 4px 0 40px rgba(0,0,0,0.5); }',
'}',
'@media (max-width: 640px) {',
'  #tabs { top: 120px; }',
'  #main { min-height: calc(100vh - 160px); }',
'  .kpi-grid { grid-template-columns: repeat(2,1fr); }',
'  .chart-grid { grid-template-columns: 1fr; }',
'  .today-bar { gap: 10px; }',
'}'
)

# ── STEP 3: New topbar HTML (replaces indices 793-807)
$newTopbar = @(
'<!-- TOPBAR -->',
'<div id="topbar">',
'  <div class="via-logo-wrap">',
'    <svg width="148" height="42" viewBox="0 0 148 42" fill="none" xmlns="http://www.w3.org/2000/svg" aria-label="VICTOR IA Tracker">',
'      <!-- Square mark -->',
'      <rect width="42" height="42" fill="#F8F7F5"/>',
'      <!-- V shape (two arms, dark ink) -->',
'      <path d="M7 8 L21 34 L35 8" stroke="#0E0F12" stroke-width="4" stroke-linejoin="round" stroke-linecap="round" fill="none"/>',
'      <!-- Animated equalizer bars -->',
'      <rect x="15" y="18" width="3" height="8" fill="#0E0F12" rx="0">',
'        <animate attributeName="height" values="8;13;5;10;8" dur="1.8s" repeatCount="indefinite" calcMode="spline" keySplines="0.4 0 0.2 1;0.4 0 0.2 1;0.4 0 0.2 1;0.4 0 0.2 1"/>',
'        <animate attributeName="y" values="18;13;21;16;18" dur="1.8s" repeatCount="indefinite" calcMode="spline" keySplines="0.4 0 0.2 1;0.4 0 0.2 1;0.4 0 0.2 1;0.4 0 0.2 1"/>',
'      </rect>',
'      <rect x="19.5" y="15" width="3" height="12" fill="#0E0F12" rx="0">',
'        <animate attributeName="height" values="12;6;16;9;12" dur="1.8s" repeatCount="indefinite" begin="0.25s" calcMode="spline" keySplines="0.4 0 0.2 1;0.4 0 0.2 1;0.4 0 0.2 1;0.4 0 0.2 1"/>',
'        <animate attributeName="y" values="15;21;11;17;15" dur="1.8s" repeatCount="indefinite" begin="0.25s" calcMode="spline" keySplines="0.4 0 0.2 1;0.4 0 0.2 1;0.4 0 0.2 1;0.4 0 0.2 1"/>',
'      </rect>',
'      <rect x="24" y="19" width="3" height="7" fill="#0E0F12" rx="0">',
'        <animate attributeName="height" values="7;15;4;11;7" dur="1.8s" repeatCount="indefinite" begin="0.5s" calcMode="spline" keySplines="0.4 0 0.2 1;0.4 0 0.2 1;0.4 0 0.2 1;0.4 0 0.2 1"/>',
'        <animate attributeName="y" values="19;12;22;15;19" dur="1.8s" repeatCount="indefinite" begin="0.5s" calcMode="spline" keySplines="0.4 0 0.2 1;0.4 0 0.2 1;0.4 0 0.2 1;0.4 0 0.2 1"/>',
'      </rect>',
'      <!-- Wordmark -->',
"      <text x=""54"" y=""19"" font-family=""'Space Grotesk', sans-serif"" font-size=""13.5"" font-weight=""600"" letter-spacing=""2.8"" fill=""#F8F7F5"">VICTOR IA</text>",
"      <text x=""55"" y=""33"" font-family=""'Space Grotesk', sans-serif"" font-size=""8.5"" font-weight=""400"" letter-spacing=""4"" fill=""rgba(248,247,245,0.38)"">TRACKER</text>",
'    </svg>',
'  </div>',
'  <span class="badge">v5.11</span>',
'  <span id="auto-live-indicator" class="auto-live-indicator" title="Auto-tracking activo">● Live</span>',
'  <div class="spacer"></div>',
'  <div class="topbar-btns">',
'    <button onclick="openAdd()">+ Entrada</button>',
'    <button onclick="exportCSV()">Export CSV</button>',
'    <button onclick="toggleSidebar()">Filtros</button>',
'    <button onclick="openFileModal()">Planeacion</button>',
'    <button id="client-mode-btn" onclick="openClientPanel()">Vista Cliente</button>',
'    <button onclick="showSettings()">Config</button>',
'  </div>',
'</div>'
)

# ── STEP 4: New tabs HTML (replaces indices 913-921)
$newTabs = @(
'<div id="tabs">',
'  <button class="tab-btn active" onclick="setTab(''dashboard'')">Dashboard</button>',
'  <button class="tab-btn" onclick="setTab(''analytics'')">Analytics</button>',
'  <button class="tab-btn" onclick="setTab(''finanzas'')">Finanzas</button>',
'  <button class="tab-btn" onclick="setTab(''organigrama'')">Organigrama</button>',
'  <button class="tab-btn" onclick="setTab(''software'')">Software &amp; APIs</button>',
'  <button class="tab-btn" onclick="setTab(''entradas'')">Entradas</button>',
'  <button class="tab-btn" onclick="setTab(''reportes'')">Reportes</button>'
)

# ── BUILD THE NEW FILE ──────────────────────────────────────────────────────
# The original structure (0-indexed):
#   [0..6]   = old head (7 lines)
#   [7]      = <style>
#   [8..788] = old CSS (781 lines)
#   [789]    = </style>
#   [790]    = </head>
#   [791]    = <body>
#   [792]    = (blank)
#   [793..807] = topbar (15 lines)
#   [808]    = blank
#   [809..812] = client panel start
#   [812]    = cp-logo line (index 812)
#   [813..912] = rest of body before tabs
#   [913..921] = tabs
#   [922..]  = rest of file

$result = [System.Collections.Generic.List[string]]::new()

# New head (replaces indices 0-7)
foreach ($l in $newHead) { $result.Add($l) }

# New CSS (replaces indices 8-788)
foreach ($l in $newCSS) { $result.Add($l) }

# Keep </style></head><body> and blank (indices 789-792)
for ($i = 789; $i -le 792; $i++) { $result.Add($lines[$i]) }

# New topbar (replaces indices 793-807)
foreach ($l in $newTopbar) { $result.Add($l) }

# Keep blank line at 808 and client panel lines 809-812 (cp-logo line is 812)
$result.Add($lines[808])  # blank

# Lines 809-811 (before cp-logo)
for ($i = 809; $i -le 811; $i++) { $result.Add($lines[$i]) }

# Line 812 = cp-logo — replace it
$result.Add('    <span class="cp-logo">VICTOR IA</span>')

# Lines 813..912 (rest of body before tabs)
for ($i = 813; $i -le 912; $i++) { $result.Add($lines[$i]) }

# New tabs (replaces indices 913-921)
foreach ($l in $newTabs) { $result.Add($l) }

# Keep rest of file from index 922 onwards (closing </div> and all JS)
for ($i = 922; $i -lt $lines.Length; $i++) { $result.Add($lines[$i]) }

# Write the file
[System.IO.File]::WriteAllLines($file, $result, [System.Text.Encoding]::UTF8)
Write-Host "Done. Result has $($result.Count) lines."
